version: '2'
services:

    nginx-api:
        image: nginx:latest
        ports:
            - "81:80"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
        depends_on:
            - php-fpm-api
            - mysql

    php-fpm-api:
        image: cytopia/php-fpm-7.1
        restart: always
        environment:
            - TIMEZONE=Europe/Berlin
            - PHP_XDEBUG_ENABLE=1
            - PHP_XDEBUG_REMOTE_HOST=localhost
            - PHP_XDEBUG_REMOTE_PORT=9000
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"

    composer:
        image: composer
        volumes:
            - "./web/app:/app"
        command: 'install --ignore-platform-reqs'

    mysql:
        image: mysql:5.7.19
        restart: always
        environment:
            - MYSQL_DATABASE=app
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - "db_data:/var/lib/mysql"
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "8088:80"
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql

volumes:
    db_data:
